name: Deployment pipeline

env:
  CONDITION: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies for backend
        run: npm i
      - name: Install dependencies for frontend
        run: npm i
        working-directory: ./2.17.puhelinluettelo
      - name: Install Playwright binaries
        run: npx playwright install --with-deps
      - name: Lint Backend
        run: npm run lint
      - name: Lint Frontend
        run: npm run lint
        working-directory: ./2.17.puhelinluettelo
      - name: Build Frontend
        run: npm run build && cp -r dist ..
        working-directory: ./2.17.puhelinluettelo
      - name: E2 Tests
        run: npm run test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
